const mockListings = [
  {
    id: 1,
    imageUrl: "../../images/house.jpg",
    title: "1 Kanal House for sale",
    address: "DHA Phase 6, Lahore",
    beds: 5,
    bath: 6,
    coveredAreaSQFT: 2350,
    propertyType: "house",
    isCommercial: false,
    price: 65000000,
  },
  {
    id: 2,
    imageUrl: "../../images/house.jpg",
    title: "Luxury Apartment for Rent",
    address: "XYZ Apartments, City Center",
    beds: 2,
    bath: 2,
    coveredAreaSQFT: 1200,
    propertyType: "apartment",
    isCommercial: false,
    price: 3000,
  },
  {
    id: 3,
    imageUrl: "../../images/house.jpg",
    title: "Spacious Family Home",
    address: "123 Green Street, Suburbia",
    beds: 4,
    bath: 3,
    coveredAreaSQFT: 2800,
    propertyType: "house",
    isCommercial: false,
    price: 500000,
  },
  {
    id: 4,
    imageUrl: "../../images/house.jpg",
    title: "Studio Apartment in the Heart of Downtown",
    address: "789 Main Avenue, Downtown",
    beds: 1,
    bath: 1,
    coveredAreaSQFT: 600,
    propertyType: "apartment",
    isCommercial: false,
    price: 1500,
  },
  {
    id: 5,
    imageUrl: "../../images/house.jpg",
    title: "Cozy Cottage with a View",
    address: "456 Serene Street, Hillside",
    beds: 2,
    bath: 1,
    coveredAreaSQFT: 800,
    propertyType: "cottage",
    isCommercial: false,
    price: 120000,
  },
  {
    id: 6,
    imageUrl: "../../images/house.jpg",
    title: "Modern Condo in Urban Living",
    address: "101 Metropolitan Avenue, Downtown",
    beds: 3,
    bath: 2,
    coveredAreaSQFT: 1600,
    propertyType: "condo",
    isCommercial: false,
    price: 450000,
  },
  {
    id: 7,
    imageUrl: "../../images/house.jpg",
    title: "Elegant Mansion with Pool",
    address: "789 Grand Boulevard, Estates",
    beds: 7,
    bath: 8,
    coveredAreaSQFT: 8000,
    propertyType: "mansion",
    isCommercial: false,
    price: 1200000,
  },
  {
    id: 8,
    imageUrl: "../../images/house.jpg",
    title: "Rustic Farmhouse with Acreage",
    address: "23 Country Road, Farmland",
    beds: 4,
    bath: 3,
    coveredAreaSQFT: 3200,
    propertyType: "farmhouse",
    isCommercial: false,
    price: 800000,
  },
  {
    id: 9,
    imageUrl: "../../images/house.jpg",
    title: "Charming Townhouse in Historic District",
    address: "456 Quaint Lane, Old Town",
    beds: 3,
    bath: 2,
    coveredAreaSQFT: 1800,
    propertyType: "townhouse",
    isCommercial: false,
    price: 350000,
  },
  {
    id: 10,
    imageUrl: "../../images/house.jpg",
    title: "Secluded Cabin in the Woods",
    address: "789 Wilderness Trail, Forest",
    beds: 2,
    bath: 1,
    coveredAreaSQFT: 1000,
    propertyType: "cabin",
    isCommercial: false,
    price: 90000,
  },
  {
    id: 11,
    imageUrl: "../../images/house.jpg",
    title: "Luxury Penthouse with Panoramic Views",
    address: "101 Skyhigh Towers, Skyline City",
    beds: 4,
    bath: 4,
    coveredAreaSQFT: 3500,
    propertyType: "apartment",
    isCommercial: false,
    price: 1200000,
  },
  {
    id: 12,
    imageUrl: "../../images/house.jpg",
    title: "Quaint Cottage with Garden",
    address: "222 Blossom Lane, Countryside",
    beds: 2,
    bath: 1,
    coveredAreaSQFT: 900,
    propertyType: "cottage",
    isCommercial: false,
    price: 130000,
  },
  {
    id: 13,
    imageUrl: "../../images/house.jpg",
    title: "Chic Loft in Historic Warehouse",
    address: "33 Industrial Avenue, Warehouse District",
    beds: 1,
    bath: 1,
    coveredAreaSQFT: 750,
    propertyType: "loft",
    isCommercial: false,
    price: 700,
  },
  {
    id: 14,
    imageUrl: "../../images/house.jpg",
    title: "Lakefront Retreat with Private Dock",
    address: "777 Lakeside Drive, Lakeside",
    beds: 3,
    bath: 2,
    coveredAreaSQFT: 1800,
    propertyType: "house",
    isCommercial: false,
    price: 550000,
  },
  {
    id: 15,
    imageUrl: "../../images/house.jpg",
    title: "Historic Mansion with Garden Estate",
    address: "101 Heritage Lane, Historical District",
    beds: 6,
    bath: 5,
    coveredAreaSQFT: 6000,
    propertyType: "mansion",
    isCommercial: false,
    price: 2500000,
  },
  {
    id: 16,
    imageUrl: "../../images/house.jpg",
    title: "Stylish Apartment with City Views",
    address: "505 Urban Way, Metropolitan City",
    beds: 2,
    bath: 2,
    coveredAreaSQFT: 1100,
    propertyType: "apartment",
    isCommercial: false,
    price: 800000,
  },
  {
    id: 17,
    imageUrl: "../../images/house.jpg",
    title: "Cosy Cabin by the Lake",
    address: "123 Tranquil Lane, Lakeside",
    beds: 1,
    bath: 1,
    coveredAreaSQFT: 600,
    propertyType: "cabin",
    isCommercial: false,
    price: 95000,
  },
  {
    id: 18,
    imageUrl: "../../images/house.jpg",
    title: "Modern Townhouse with Rooftop Garden",
    address: "789 Urban Gardens, Downtown",
    beds: 3,
    bath: 2,
    coveredAreaSQFT: 1600,
    propertyType: "townhouse",
    isCommercial: false,
    price: 550000,
  },
  {
    id: 19,
    imageUrl: "../../images/house.jpg",
    title: "Elegant Estate with Fountain Courtyard",
    address: "101 Grand Manor, Suburbia",
    beds: 5,
    bath: 4,
    coveredAreaSQFT: 4500,
    propertyType: "estate",
    isCommercial: false,
    price: 1800000,
  },
  {
    id: 20,
    imageUrl: "../../images/house.jpg",
    title: "Charming Cottage in the Countryside",
    address: "33 Serenity Lane, Countryside",
    beds: 2,
    bath: 1,
    coveredAreaSQFT: 1000,
    propertyType: "cottage",
    isCommercial: false,
    price: 110000,
  },
  {
    id: 21,
    imageUrl: "../../images/house.jpg",
    title: "Luxury Condo with Skyline Views",
    address: "505 Highrise Towers, Downtown",
    beds: 2,
    bath: 2,
    coveredAreaSQFT: 1400,
    propertyType: "condo",
    isCommercial: false,
    price: 720000,
  },
  {
    id: 22,
    imageUrl: "../../images/house.jpg",
    title: "Rustic Cabin Retreat in the Mountains",
    address: "789 Mountain Pass, Alpine",
    beds: 1,
    bath: 1,
    coveredAreaSQFT: 800,
    propertyType: "cabin",
    isCommercial: false,
    price: 75000,
  },
  {
    id: 23,
    imageUrl: "../../images/house.jpg",
    title: "Historic Brownstone with Classic Charm",
    address: "123 Vintage Street, Historic District",
    beds: 4,
    bath: 3,
    coveredAreaSQFT: 2800,
    propertyType: "brownstone",
    isCommercial: false,
    price: 950000,
  },
  {
    id: 24,
    imageUrl: "../../images/house.jpg",
    title: "Seaside Villa with Panoramic Ocean Views",
    address: "101 Oceanfront Drive, Seaside",
    beds: 6,
    bath: 5,
    coveredAreaSQFT: 5000,
    propertyType: "villa",
    isCommercial: false,
    price: 2800000,
  },
  {
    id: 25,
    imageUrl: "../../images/house.jpg",
    title: "Urban Loft with Industrial Aesthetics",
    address: "505 Loft Avenue, Urban District",
    beds: 1,
    bath: 1,
    coveredAreaSQFT: 900,
    propertyType: "loft",
    isCommercial: false,
    price: 600,
  },
  {
    id: 26,
    imageUrl: "../../images/house.jpg",
    title: "Stylish Townhouse in the Heart of the City",
    address: "789 Trendy Street, Metropolitan City",
    beds: 3,
    bath: 2,
    coveredAreaSQFT: 1800,
    propertyType: "townhouse",
    isCommercial: false,
    price: 600000,
  },
  {
    id: 27,
    imageUrl: "../../images/house.jpg",
    title: "Charming Cottage with Garden Oasis",
    address: "22 Serene Lane, Countryside",
    beds: 2,
    bath: 1,
    coveredAreaSQFT: 1100,
    propertyType: "cottage",
    isCommercial: false,
    price: 145000,
  },
  {
    id: 28,
    imageUrl: "../../images/house.jpg",
    title: "Modern Apartment with Luxury Amenities",
    address: "101 Urban Living, Downtown",
    beds: 2,
    bath: 2,
    coveredAreaSQFT: 1300,
    propertyType: "apartment",
    isCommercial: false,
    price: 900000,
  },
  {
    id: 29,
    imageUrl: "../../images/house.jpg",
    title: "Beautiful Villa with a Garden Oasis",
    address: "22 Tranquil Lane, Countryside",
    beds: 3,
    bath: 2,
    coveredAreaSQFT: 1800,
    propertyType: "villa",
    isCommercial: false,
    price: 450000,
  },
  {
    id: 30,
    imageUrl: "../../images/house.jpg",
    title: "Cozy Cabin Retreat in the Woods",
    address: "42 Rustic Road, Wilderness",
    beds: 2,
    bath: 1,
    coveredAreaSQFT: 800,
    propertyType: "cabin",
    isCommercial: false,
    price: 80000,
  },
  {
    id: 31,
    imageUrl: "../../images/house.jpg",
    title: "Modern Studio Apartment for Rent",
    address: "123 Loft Street, Metropolitan City",
    beds: 1,
    bath: 1,
    coveredAreaSQFT: 600,
    propertyType: "apartment",
    isCommercial: false,
    price: 2200,
  },
  {
    id: 32,
    imageUrl: "../../images/house.jpg",
    title: "Spacious Family Home with Garden",
    address: "456 Green Acres, Suburbia",
    beds: 4,
    bath: 3,
    coveredAreaSQFT: 2400,
    propertyType: "house",
    isCommercial: false,
    price: 550000,
  },
  {
    id: 33,
    imageUrl: "../../images/house.jpg",
    title: "Chic Urban Loft with Open Layout",
    address: "789 Metro Loft, Downtown",
    beds: 1,
    bath: 1,
    coveredAreaSQFT: 800,
    propertyType: "loft",
    isCommercial: false,
    price: 750,
  },
  {
    id: 34,
    imageUrl: "../../images/house.jpg",
    title: "Country Retreat with Panoramic Views",
    address: "101 Countryside Road, Hillside",
    beds: 3,
    bath: 2,
    coveredAreaSQFT: 1800,
    propertyType: "house",
    isCommercial: false,
    price: 420000,
  },
];

export default mockListings;
